### ISSUE TITLE
Why removing mapzen token?

### ISSUE THREAD

**Issue by eauchat** [YunoHost-Apps/facilmap_ynh#11]
@ericgaspar I was wondering why you decided to remove the MAPZEN_TOKEN.
According to [facilmap documentaion](https://docs.facilmap.org/developers/server/config.html), the token is necessary to display elevation info in facilmap. Some admins might want this feature.
Just to understand the reason behind this modification :)

**Comment by ericgaspar** [comment]
As far as I remember MAPZEN_TOKEN sign in page was not active anymore (or changed to another place): https://www.mapzen.com/developers/sign_up

**Comment by cdauth** [comment]
FYI: The Mapzen feature has been disabled for a while due to technical difficulties. It used to be used to get the elevation of markers and search results. The token is still configurable because I was planning to add the functionality again at some point.

**Comment by eauchat** [comment]
Ok cool.
Then maybe we can keep things as they are for now. And when facilmap will use mapzen again, reimplement it here as well.
