### ISSUE TITLE
Can access be restricted?

### ISSUE THREAD

**Issue by mattbk** [YunoHost-Apps/facilmap_ynh#15]
It seems like anyone with the URL can set up a new map. Is there a way to restrict that?

**Comment by eauchat** [comment]
I don't think facilmap itself has this functionality. But it's worth checking the [upstream repository](https://github.com/FacilMap/facilmap/) and ask there, maybe the developers will be interested in implementing such functionality.

On yunohost side, I don't see something that could be done to customize facilmap. You can install the app as private, but then only your server users will be able to see maps and use facilmap.
