### ISSUE TITLE
wrong install path

### ISSUE THREAD

**Issue by Ddataa** [YunoHost-Apps/facilmap_ynh#16]
### Describe the bug

App is not installed in standard yunohost path

### Context

- Hardware: VPS bought online
- YunoHost version: latest stable
- I have access to my server: through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

https://github.com/YunoHost-Apps/facilmap_ynh/blob/a3a904754e37c5549604434b43a8662c4ed05749/scripts/install#L46

### Expected behavior

install in standard path /var/www/

**Comment by eauchat** [comment]
I believe `/opt/yunohost/` is [the standard yunohost path for nodejs apps](https://github.com/YunoHost/example_ynh/blob/master/scripts/install#L59-L61).
If I'm not mistaken `/var/www/` is for HTML/PHP apps.
Did I misunderstand something?

**Comment by Ddataa** [comment]
you didn't

I did.
Sorry for bothering
