### ISSUE TITLE
Upgrading to 4.1.1 results in "Could not load facilmap"

### ISSUE THREAD

**Issue by cloo** [YunoHost-Apps/facilmap_ynh#25]
Upgrading Facilmap from 3.4.0 to 4.1.1 appears to go flawlessly, but UI only shows a message "Could not load FacilMap"
![image](https://github.com/YunoHost-Apps/facilmap_ynh/assets/651760/3ea225e8-bc8e-4825-9f9e-1f93a1ac373b)

Facilmap service is running.
Upgrade log: https://paste.yunohost.org/raw/fasuxomisi

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 11.2.17
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

**Comment by StarSyth** [comment]
I have the same issue

**Comment by cdauth** [comment]
Could you share a link to a broken instance, or at least share the output of the browser console?

**Comment by cloo** [comment]
thanks @cdauth for looking at it. [The site is here](https://dudenas.lt/maps/). I will probably downgrade it soon-ish, because I need functionality, so when I do, [html output is here](https://pastebin.com/z57Pmt1s).

**Comment by cdauth** [comment]
In v4.0.0, the JavaScript files have moved under `/_app/` (sorry, I should probably have documented this somewhere). It seems that YunoHost requires SSO for that, so the JavaScript files forward to a login form. I’m not familiar enough with YunoHost to understand why this is happening. @ericgaspar any ideas?

**Comment by cdauth** [comment]
Asked here: https://forum.yunohost.org/t/app-is-redirected-to-sso-login-page/30241

**Comment by cdauth** [comment]
I have identified the problem and will be working on a fix soon.

For now it seems like it only works when FacilMap runs on the root path (`/`) of the domain.

**Comment by cdauth** [comment]
I have released FacilMap 4.1.2, which should fix the problem. I don't know how the YunoHost upgrade cycle works and when the new version will be available there.

**Comment by cdauth** [comment]
The new version seems to be available now. Upgrading should fix the issue. Please report any further issues that you encounter.
