### ISSUE TITLE
Update to 3.4.0? :)

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/facilmap_ynh#7]
This YNH version is 3.1.0 and I was wondering if you plan to update to 3.4.0 since you skipped a few versions and I am wondering if this could break a facilmap install if there are more and more versions skipped. Cheers and thanks for your work!

**Comment by tio-trom** [comment]
Ah I see it is 3.3.0 but you didn't update that in the Readme.

**Comment by eauchat** [comment]
Seems the readme has been fixed.
